### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by esen96** [oyuz/NGAC-graph-UI#2]
- [x] Create a zoom bar + buttons in the bottom right corner

- [x] Create an NGAC policy tool header

- [x]  Fix grid layout for parent graph nodes and cluster its children

- [x] Take permission input upon edge connection

- [x] Create side panel for interactive graph tools

- [x] Create and organize file system, separate cytoscape files and project js file

- [x] Adjust default layout zoom to accomodate new panel buttons

- [x] Fix sticky button positioning, align with zoom panel

- [x] Deliniate objects and users in the graph system

- [x] Create popup menu fields for adding nodes and relations 

- [x]  Display toggle focus for edit and pan mode

- [x] Fix positioning for newly added nodes

- [x] Patch double draw toggle bug with overlay if edgehandles devs don't respond to issue

- [x] Styling: make labels more visible 

- [x] Fix double toggle display bug 

- [x] See if there is a fix for layout snapping issue (deprecated, see if it reappears)

- [x] Create overlay typing for attributes

- [x] Determine if we separate user- and object type in graph system (deprecated)

- [x] Only load attributes to select field once to avoid duplication

- [x] Create a file parser for loading data from a policy file

- [x] Add new attributes to select field in node prompt

- [x] Examine whitespace username bug (fixed by local overlay function)

- [x] Add close button functionality in window prompts

- [x] Enforce edge constraint: only user attribute to object attribute 

- [x] List only viable select options by type

- [x] Separate visual representation of user- and object attributes

- [x] Find a layout appropriate for new clustering (fixed by changing default values in layout extension)

- [x] Implement toggle for rendering layout on adding element, find a design method for non updating layout

- [x] Filehandler: fix double access right issue

- [x] Filehandler: handle double assign parent issue

**Comment by oyuz** [comment]
- [ ] Take permission input upon edge connection
- [ ] Create side panel for interactive graph tools 
- [ ] Create navigation fold-out bar for file ops

**Comment by oyuz** [comment]
- [ ] Create and organize file system, separate cytoscape files and project js file

**Comment by oyuz** [comment]
- [ ] Adjust default zoom to accomodate new panel buttons
- [ ] Fix sticky button positioning, align with zoom panel

**Comment by oyuz** [comment]
- [ ] Deliniate objects and users in the graph system
