### ISSUE TITLE
Task list #2

### ISSUE THREAD

**Issue by esen96** [oyuz/NGAC-graph-UI#3]
- [x] Create an option to promote user or object to additional parents

- [x] Select users and objects from db in db options menu

- [x] Add entry prompt for selecting a file when first opening page

- [x] Investigate file dependencies from rest of project with db handling

- [x] Header
